theme='risotto'
baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Justin Horner'
author = 'Justin Horner'
DefaultContentLanguage = "en"
enableInlineShortcodes = true

# Automatically add content sections to main menu
sectionPagesMenu = "main"

[params]
noindex = false

[params.theme]
palette = "gruvbox-dark"

# Sidebar: about/bio
[params.about]
title = "Justin Horner"
description = "Game Programmer and Software Engineer at Meta, Supernatural"
logo = "profile.png"

# Sidebar: social links
# Available icon sets:
# * FontAwesome 6 <https://fontawesome.com/> ('fa-brands', 'fa-normal', or 'fa-solid' for brands)
# * Academicons <https://jpswalsh.github.io/academicons> ('ai ai-')
[[params.socialLinks]]
icon = "fa-brands fa-twitch"
title = "Twitch"
url = "https://orcid.org/0000-0001-2345-6789"

[[params.socialLinks]]
icon = "fa-brands fa-x-twitter"
title = "Twitter"
url = "https://twitter.com/justinhhorner"

[[params.socialLinks]]
icon = "fa-brands fa-linkedin"
title = "LinkedIn"
url = "https://linkedin.com/in/justinhhorner"

[[params.socialLinks]]
icon = "fa-brands fa-youtube"
title = "YouTube"
url = "https://orcid.org/0000-0001-2345-6789"

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/justinhhorner"
